# Generated by Django 2.1.7 on 2019-05-16 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='Title')),
                ('post_text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create data')),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Post',
                'db_table': 'post',
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('logo', models.ImageField(blank=True, help_text='50x50', null=True, upload_to='logo/', verbose_name='Logo')),
                ('full_name', models.CharField(max_length=25, verbose_name='Full name')),
                ('uniq_identifi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь отправителя')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile', verbose_name='Post autor'),
        ),
    ]
